const fs = require('fs');
const path = require('path');

// Read environment variables
const isDevelopment = process.env.NODE_ENV !== 'production';
const apiUrl = isDevelopment ? 'http://localhost:8000' : process.env.NEXT_PUBLIC_API_URL;
const runpodApiKey = process.env.RUNPOD_API_KEY; // Include if your frontend needs it (unlikely for direct API calls)
const runpodEndpointId = process.env.RUNPOD_ENDPOINT_ID; // Include if needed

// Validate API URL in production
if (!isDevelopment && !apiUrl) {
    console.error('ERROR: Environment variable NEXT_PUBLIC_API_URL is not set in production!');
    process.exit(1); // Exit with error code
}

// Content for config.js
const configContent = `// This file is generated by build-config.js\nconst config = {\n    apiUrl: ${JSON.stringify(apiUrl)},\n    endpoints: {\n        sentiment: 'sentiment',\n        mentalHealth: 'mental-health',\n        counsel: 'counsel',\n        all: 'all',\n        keyPoints: 'key-points',\n        clearHistory: 'clear-history',\n    }\n};\n\nexport default config;\n`;

// Define output path
const outputPath = path.join(__dirname, 'frontend', 'public', 'js', 'config.js');

// Write the file
fs.writeFileSync(outputPath, configContent);

console.log(`Successfully generated config.js at ${outputPath} with apiUrl: ${apiUrl}`); 